services:
  - type: web
    name: routeboard
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: BACKEND_URL
        fromService:
          type: web
          name: routeboard-api
          envVarKey: RENDER_EXTERNAL_URL
